# TASK 1
dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [75]:
import pandas as pd

data=pd.read_csv("vgsalesGlobale.csv")
data.head()
#------------------------------ total global sale -----------------------
total=data['Global_Sales'].sum()
print("Total Global Sale, ",total)


#------------------------------ Sale for each region -----------------------
s1=data['NA_Sales'].mean()
s2=data['EU_Sales'].mean()
s3=data['JP_Sales'].mean()
s4=data['Other_Sales'].mean()

print(f'\n\nAverage Sale for EU is {s2}, JP is {s3}, NA is {s1} and others {s4} ')

#---------------------------------- Display last 10 rows.----------------------
data.tail(10)


Total Global Sale,  8920.44


Average Sale for EU is 0.14665200626581515, JP is 0.077781660441017, NA is 0.26466742981082064 and others 0.0480630196409206 


Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [76]:
#------------------------------ highest global sale -----------------------
highest=data.sort_values('Global_Sales',ascending=False)
print("\n\n Top 5 highest selling games are: ")
highest[['Name','Global_Sales']].head()



 Top 5 highest selling games are: 


Name  Global_Sales
0                Wii Sports         82.74
1         Super Mario Bros.         40.24
2            Mario Kart Wii         35.82
3         Wii Sports Resort         33.00
4  Pokemon Red/Pokemon Blue         31.37

In [77]:
#------------------------------ Top 5 genres -----------------------
highest=data.sort_values('Global_Sales',ascending=False)
print("\n\n Top 5 highest selling games are: ")
highest[['Genre','Global_Sales']].head()



 Top 5 highest selling games are: 


Genre  Global_Sales
0        Sports         82.74
1      Platform         40.24
2        Racing         35.82
3        Sports         33.00
4  Role-Playing         31.37

In [78]:
#-----------------------------Calculate the total sales for each genre--------------------
na=data.groupby('Genre')[['NA_Sales','Global_Sales']].sum()
eu=data.groupby('Genre')[['EU_Sales','Global_Sales']].sum()
jp=data.groupby('Genre')[['JP_Sales','Global_Sales']].sum()
ot=data.groupby('Genre')[['Other_Sales','Global_Sales']].sum()
print('sales for each genre in each region\n\n',na,eu,jp,ot)

sales for each genre in each region

               NA_Sales  Global_Sales
Genre                               
Action          877.83       1751.18
Adventure       105.80        239.04
Fighting        223.59        448.91
Misc            410.24        809.96
Platform        447.05        831.37
Puzzle          123.78        244.95
Racing          359.42        732.04
Role-Playing    327.28        927.37
Shooter         582.60       1037.37
Simulation      183.31        392.20
Sports          683.35       1330.93
Strategy         68.70        175.12               EU_Sales  Global_Sales
Genre                               
Action          525.00       1751.18
Adventure        64.13        239.04
Fighting        101.32        448.91
Misc            215.98        809.96
Platform        201.63        831.37
Puzzle           50.78        244.95
Racing          238.39        732.04
Role-Playing    188.06        927.37
Shooter         313.27       1037.37
Simulation      113.38        392.20


In [80]:
#-----------------------------Platforms--------------------
highest=data.sort_values('Global_Sales',ascending=False)
print("\n\n Top 3 gaming platforms  are: ")
highest[['Platform','Global_Sales']].head(3)



 Top 3 gaming platforms  are: 


Platform  Global_Sales
0      Wii         82.74
1      NES         40.24
2      Wii         35.82

In [79]:
#-----------------------------Market share--------------------
sale=data.groupby('Genre')['Global_Sales'].sum()
gsale=sale.sum()
print('Market share is: ',sale/gsale*100)

Market share is:  Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [81]:
#-------------------------------Corelation--------------------
co=data['NA_Sales'].corr(data['EU_Sales'])
print('Correlation bw NA and EU is: ',co)

Correlation bw NA and EU is:  0.7677267483702631


## Task 2 English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [82]:
spanish={"hello":"Holla",
 "good":"Bueno",
 "bad":"Malo",
 "best":"Mejor",
 "scam":"Estafa",
 "fine":"Bien/Aceptable",
 "find":"Encontrar",
 "close":"Cerrar",
 "open":"Abrir"
 }
exit=0
while(1):
  word=input("Entor english word or exit: ")
  word.lower()
  if word=='exit':
    break
  for eng in spanish:

    if word==eng:
      print('Spanish Translation is: ',spanish[eng])
      exit=1
      break
  if exit==0:
    print('Word not found.\n')
    exit=1





Entor english word or exit: good
Spanish Translation is:  Bueno
Entor english word or exit: edfr
Entor english word or exit: exit



## Task 3 Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [83]:
def classify(emails):

    important = []
    promotions = []
    spam = []
    imp = ['urgent', 'important', 'action required', 'please respond']
    prom = ['sale', 'discount', 'offer', 'limited time', 'buy now']
    sp = ['win', 'free', 'click here', 'congratulations', 'prize', 'exclusive offer']

    for email in emails:

        if any(k in email for k in imp):
            important.append(email)

        elif any(k in email for k in prom):
            promotions.append(email)

        elif any(k in email for k in sp):
            spam.append(email)

    return imp, prom, sp

emails = [
    "URGENT: Action Required for Your Account",
    "Limited Time Offer: 50% off your next purchase",
    "Congratulations! You have won a free prize",
    "Please respond: Important Update for Your Account",
    "Exclusive Offer: Buy 1 get 1 free on all items",
    "Click here to claim your prize"
]

important, promotions, spam = classify(emails)

print("Important Emails:")
for email in important:
    print(email)

print("\nPromotions Emails:")
for email in promotions:
    print(email)

print("\nSpam Emails:")
for email in spam:
    print(email)


Important Emails:
urgent
important
action required
please respond

Promotions Emails:
sale
discount
offer
limited time
buy now

Spam Emails:
win
free
click here
congratulations
prize
exclusive offer


## Task 4 Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

In [71]:
shopping_cart = []
print('---------------------------Welcome to Shop-----------------\n\n\nHere are the Products\n\n')

prod = {
    "1": "T-shirt 300pkr",
    "2": "Sweat Shirt 400pkr",
    "3": "Hoodie 500pkr"
}

for x in prod:
    print(x, prod[x])

choice = ''
while choice != 'q':
    ask = input('Select From the menu ( 1, 2, 3 ) or press "q" to exit and checkout: ')
    if ask == 'q':
        choice = ask
    elif ask in prod:
        shopping_cart.append(prod[ask])
        print('Added into your cart.\n')
    else:
        print('Incorrect choice.\n')

print('\nYour Shopping Cart:')
for x in shopping_cart:
    print(x,'\n\nGOOD BYE :)')


---------------------------Welcome to Shop-----------------


Here are the Products


1 T-shirt 300pkr
2 Sweat Shirt 400pkr
3 Hoodie 500pkr
Select From the menu ( 1, 2, 3 ) or press "q" to exit and checkout: 1
Added into your cart.

Select From the menu ( 1, 2, 3 ) or press "q" to exit and checkout: q

Your Shopping Cart:
T-shirt 300pkr 

GOOD BYE :)


## Task 5
* Create two NumPy arrays of the same shape and perform element-wise addition on them.
* Calculate the element-wise product of two NumPy arrays.

In [49]:
import numpy as np
arr1=np.array([10,23,32,45,67,44,34,54,21,1])
arr2=np.array([20,33,52,15,64,42,31,34,13,19])
print(f'Arr1: {arr1}\nArr2: {arr2}\nProduct')
for x in range(10):
  print(arr1[x]*arr2[x])

Arr1: [10 23 32 45 67 44 34 54 21  1]
Arr2: [20 33 52 15 64 42 31 34 13 19]
Product
200
759
1664
675
4288
1848
1054
1836
273
19


## Task 6
* Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

* Concatenate two NumPy arrays horizontally and vertically.

In [59]:
import numpy as np
arr1=np.array([10,23,32,45,67,44,34,54,21,1,2,3])
arr2=np.array([20,33,52,15,64,42,31,34,13,19,20,29])
x=arr1.reshape(3,4)
y=arr2.reshape(3,4)
print(f'Arr1:\n{x}\n\nArr2:\n{y}')

z=np.concatenate((x,y))
print(f'\n\nConcatinated array:\n{z}')


Arr1:
[[10 23 32 45]
 [67 44 34 54]
 [21  1  2  3]]

Arr2:
[[20 33 52 15]
 [64 42 31 34]
 [13 19 20 29]]


Concatinated array:
[[10 23 32 45]
 [67 44 34 54]
 [21  1  2  3]
 [20 33 52 15]
 [64 42 31 34]
 [13 19 20 29]]


## Task 7
* Reverse A List In Python Using Slicing


In [61]:
listt=[1,2,3,4,5,6,7,8]
print(f'List is: {listt}')
rev=listt[::-1]
print(f'Reversed list is: {rev}')

List is: [1, 2, 3, 4, 5, 6, 7, 8]
Reversed list is: [8, 7, 6, 5, 4, 3, 2, 1]


# TASK 8
You need to download the GitHub Desktop software, push your lab task to your GitHub account, and share the link on GCR as a submission.